# Rollback from opencast deployment
---
- name: Rollback Opencast
  hosts: all
  become: true
  vars:
    script_action: "Rollback"
    deploy_script: "{{ folder_script }}files/rollback.sh"
    deploy_logfile: "{{ folder_script }}log/{{ script_action | lower }}.{{ deploy_date_time | regex_replace(' ','.') | regex_replace(':','-') }}.log"

  pre_tasks:
    - name: Create log file
      local_action: template src="{{ folder_script }}templates/tmpl-deploy.j2" dest="{{ deploy_logfile }}"
      run_once: True

  roles:
    - rollback

  post_tasks:
    - include_role:
        name: jira_comment
      when: production|bool