# Check servers
---
- name: Check the versions on Worker / Admin servers (NOT Ingest)
  hosts: all
  become: true

  roles:
    - { role: check_software_versions,  when: "'ingest' not in group_names"} # not for ingest nodes