# Start All Opencast Services
---
- name: Start All Opencast Services
  hosts: all
  become: true

  pre_tasks:

  roles:

  post_tasks:
    - name: Start Opencast
      service: name=opencast state=started
      #when: start_service|bool
      ignore_errors: yes
