# Stop All Opencast Services
---
- name: Stop All Opencast Services
  hosts: all
  become: true

  pre_tasks:

  roles:

  post_tasks:
    - name: Stop Opencast
      service: name=opencast state=stopped
      #when: start_service|bool
      ignore_errors: yes
